firstName = str("John")
lastName = str("Smith")
age = int(100)
ssn = int(12345)
height = float(171.5)
weight = float(68.3)

print(firstName, lastName, age, ssn, height, weight)
print(type(firstName))
print(type(lastName))
print(type(age))
print(type(ssn))
print(type(height))
print(type(weight))